2019-01-29 15:22:37,522 - DEBUG - debug message
2019-01-29 15:22:37,522 - INFO - info message
2019-01-29 15:22:37,522 - WARNING - warning message
2019-01-29 15:22:37,523 - ERROR - error message
2019-01-29 15:22:37,523 - CRITICAL - critical message
2019-01-29 15:26:35,417 - logging_test.py[line: 22] - DEBUG - debug message: 0
2019-01-29 15:26:35,417 - logging_test.py[line: 23] - INFO - info message: 0
2019-01-29 15:26:35,417 - logging_test.py[line: 24] - WARNING - warning message: 0
2019-01-29 15:26:35,417 - logging_test.py[line: 25] - ERROR - error message: 0
2019-01-29 15:26:35,417 - logging_test.py[line: 26] - CRITICAL - critical message: 0
2019-01-29 15:26:35,418 - logging_test.py[line: 22] - DEBUG - debug message: 1
2019-01-29 15:26:35,418 - logging_test.py[line: 23] - INFO - info message: 1
2019-01-29 15:26:35,418 - logging_test.py[line: 24] - WARNING - warning message: 1
2019-01-29 15:26:35,418 - logging_test.py[line: 25] - ERROR - error message: 1
2019-01-29 15:26:35,418 - logging_test.py[line: 26] - CRITICAL - critical message: 1
2019-01-29 15:26:35,419 - logging_test.py[line: 22] - DEBUG - debug message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 23] - INFO - info message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 24] - WARNING - warning message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 25] - ERROR - error message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 26] - CRITICAL - critical message: 2
2019-01-29 15:26:35,419 - logging_test.py[line: 22] - DEBUG - debug message: 3
2019-01-29 15:26:35,419 - logging_test.py[line: 23] - INFO - info message: 3
2019-01-29 15:26:35,419 - logging_test.py[line: 24] - WARNING - warning message: 3
2019-01-29 15:26:35,419 - logging_test.py[line: 25] - ERROR - error message: 3
2019-01-29 15:26:35,419 - logging_test.py[line: 26] - CRITICAL - critical message: 3
2019-01-29 15:26:35,420 - logging_test.py[line: 22] - DEBUG - debug message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 23] - INFO - info message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 24] - WARNING - warning message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 4
2019-01-29 15:26:35,420 - logging_test.py[line: 22] - DEBUG - debug message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 23] - INFO - info message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 24] - WARNING - warning message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 5
2019-01-29 15:26:35,420 - logging_test.py[line: 22] - DEBUG - debug message: 6
2019-01-29 15:26:35,420 - logging_test.py[line: 23] - INFO - info message: 6
2019-01-29 15:26:35,420 - logging_test.py[line: 24] - WARNING - warning message: 6
2019-01-29 15:26:35,420 - logging_test.py[line: 25] - ERROR - error message: 6
2019-01-29 15:26:35,420 - logging_test.py[line: 26] - CRITICAL - critical message: 6
2019-01-29 15:26:35,421 - logging_test.py[line: 22] - DEBUG - debug message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 23] - INFO - info message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 24] - WARNING - warning message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 7
2019-01-29 15:26:35,421 - logging_test.py[line: 22] - DEBUG - debug message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 23] - INFO - info message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 24] - WARNING - warning message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 8
2019-01-29 15:26:35,421 - logging_test.py[line: 22] - DEBUG - debug message: 9
2019-01-29 15:26:35,421 - logging_test.py[line: 23] - INFO - info message: 9
2019-01-29 15:26:35,421 - logging_test.py[line: 24] - WARNING - warning message: 9
2019-01-29 15:26:35,421 - logging_test.py[line: 25] - ERROR - error message: 9
2019-01-29 15:26:35,421 - logging_test.py[line: 26] - CRITICAL - critical message: 9
2019-01-29 15:35:00,539 - logging_test.py[line: 29] - DEBUG - debug message: 0
2019-01-29 15:35:00,539 - logging_test.py[line: 30] - INFO - info message: 0
2019-01-29 15:35:00,539 - logging_test.py[line: 31] - WARNING - warning message: 0
2019-01-29 15:35:00,539 - logging_test.py[line: 32] - ERROR - error message: 0
2019-01-29 15:35:00,540 - logging_test.py[line: 33] - CRITICAL - critical message: 0
2019-01-29 15:35:01,541 - logging_test.py[line: 29] - DEBUG - debug message: 1
2019-01-29 15:35:01,541 - logging_test.py[line: 30] - INFO - info message: 1
2019-01-29 15:35:01,542 - logging_test.py[line: 31] - WARNING - warning message: 1
2019-01-29 15:35:01,543 - logging_test.py[line: 32] - ERROR - error message: 1
2019-01-29 15:35:01,543 - logging_test.py[line: 33] - CRITICAL - critical message: 1
2019-01-29 15:35:02,544 - logging_test.py[line: 29] - DEBUG - debug message: 2
2019-01-29 15:35:02,544 - logging_test.py[line: 30] - INFO - info message: 2
2019-01-29 15:35:02,544 - logging_test.py[line: 31] - WARNING - warning message: 2
2019-01-29 15:35:02,544 - logging_test.py[line: 32] - ERROR - error message: 2
2019-01-29 15:35:02,544 - logging_test.py[line: 33] - CRITICAL - critical message: 2
2019-01-29 15:35:03,545 - logging_test.py[line: 29] - DEBUG - debug message: 3
2019-01-29 15:35:03,545 - logging_test.py[line: 30] - INFO - info message: 3
2019-01-29 15:35:03,546 - logging_test.py[line: 31] - WARNING - warning message: 3
2019-01-29 15:35:03,546 - logging_test.py[line: 32] - ERROR - error message: 3
2019-01-29 15:35:03,547 - logging_test.py[line: 33] - CRITICAL - critical message: 3
2019-01-29 15:35:04,549 - logging_test.py[line: 29] - DEBUG - debug message: 4
2019-01-29 15:35:04,549 - logging_test.py[line: 30] - INFO - info message: 4
2019-01-29 15:35:04,550 - logging_test.py[line: 31] - WARNING - warning message: 4
2019-01-29 15:35:04,550 - logging_test.py[line: 32] - ERROR - error message: 4
2019-01-29 15:35:04,551 - logging_test.py[line: 33] - CRITICAL - critical message: 4
2019-01-29 15:35:05,552 - logging_test.py[line: 29] - DEBUG - debug message: 5
2019-01-29 15:35:05,552 - logging_test.py[line: 30] - INFO - info message: 5
2019-01-29 15:35:05,553 - logging_test.py[line: 31] - WARNING - warning message: 5
2019-01-29 15:35:05,554 - logging_test.py[line: 32] - ERROR - error message: 5
2019-01-29 15:35:05,554 - logging_test.py[line: 33] - CRITICAL - critical message: 5
2019-01-29 15:35:06,555 - logging_test.py[line: 29] - DEBUG - debug message: 6
2019-01-29 15:35:06,556 - logging_test.py[line: 30] - INFO - info message: 6
2019-01-29 15:35:06,557 - logging_test.py[line: 31] - WARNING - warning message: 6
2019-01-29 15:35:06,557 - logging_test.py[line: 32] - ERROR - error message: 6
2019-01-29 15:35:06,558 - logging_test.py[line: 33] - CRITICAL - critical message: 6
2019-01-29 15:35:07,559 - logging_test.py[line: 29] - DEBUG - debug message: 7
2019-01-29 15:35:07,560 - logging_test.py[line: 30] - INFO - info message: 7
2019-01-29 15:35:07,560 - logging_test.py[line: 31] - WARNING - warning message: 7
2019-01-29 15:35:07,561 - logging_test.py[line: 32] - ERROR - error message: 7
2019-01-29 15:35:07,562 - logging_test.py[line: 33] - CRITICAL - critical message: 7
2019-01-29 15:35:08,563 - logging_test.py[line: 29] - DEBUG - debug message: 8
2019-01-29 15:35:08,563 - logging_test.py[line: 30] - INFO - info message: 8
2019-01-29 15:35:08,564 - logging_test.py[line: 31] - WARNING - warning message: 8
2019-01-29 15:35:08,564 - logging_test.py[line: 32] - ERROR - error message: 8
2019-01-29 15:35:08,565 - logging_test.py[line: 33] - CRITICAL - critical message: 8
2019-01-29 15:35:09,567 - logging_test.py[line: 29] - DEBUG - debug message: 9
2019-01-29 15:35:09,568 - logging_test.py[line: 30] - INFO - info message: 9
2019-01-29 15:35:09,568 - logging_test.py[line: 31] - WARNING - warning message: 9
2019-01-29 15:35:09,569 - logging_test.py[line: 32] - ERROR - error message: 9
2019-01-29 15:35:09,570 - logging_test.py[line: 33] - CRITICAL - critical message: 9
